# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/development/cicd/templates/
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# GitLab CI Cache with Nix is based on https://gitlab.com/Cynerd/gitlab-ci-nix

.nix:
  image: nixos/nix
  variables:
    RUNNER_AFTER_SCRIPT_TIMEOUT: 30m
  cache:
    key: "nix"
    paths:
      - ".nix-cache"
  before_script:
    - echo "experimental-features = nix-command flakes" >>/etc/nix/nix.conf
    - cachedir="$(pwd)/.nix-cache"
    - |
      if [ -d "$cachedir" ]; then echo "extra-substituters = file://$cachedir?priority=10&trusted=true" \ >>/etc/nix/nix.conf
      fi
    - find /nix/store -mindepth 1 -maxdepth 1 ! -name \*.drv | sort >/nix/.before
  after_script:
    - echo 'Assemble list of new builds'
    - find /nix/store -mindepth 1 -maxdepth 1 ! -name \*.drv | sort >/nix/.after
    - comm -13 /nix/.before /nix/.after >/nix/.new
    - if ! [ -s /nix/.new ]; then exit 0; fi
    - echo 'Export new builds to Gitlab CI Runner cache'
    - |
      if [ -z "${NO_NIX_CACHE:-}" ]; then
        xargs -a /nix/.new nix copy --to "file://$(pwd)/.nix-cache"
      fi

stages:
  - build-vms
  - test

# BUILD STAGE
#============================================================

build-vm-cve-2020-7247-opensmtpd:
  extends: .nix
  stage: build-vms
  script:
    - echo "Starting VM build for CVE-2020-7247 OpenSMTPD vulnerability..."
    - cd ./cves/cve-2020-7247-opensmtpd
    - nix build .#vmServer -L
  allow_failure: true

build-vm-cve-2014-0160-heartbleed:
  extends: .nix
  stage: build-vms
  script:
    - echo "Starting VM build for CVE-2014-0160 Heartbleed vulnerability..."
    - cd ./cves/cve-2014-0160-heartbleed
    - nix build .#vmServer -L
  allow_failure: true

build-vm-cve-2023-22809:
  extends: .nix
  stage: build-vms
  script:
    - echo "Starting VM build for CVE-2023-22809 vulnerability..."
    - cd ./cves/cve-2023-22809
    - nix build .#vmServer -L
  allow_failure: true

build-vm-cve-2021-4034-pwnkit:
  extends: .nix
  stage: build-vms
  script:
    - echo "Starting VM build for CVE-2021-4034 PwnKit vulnerability..."
    - cd ./cves/cve-2021-4034-pwnkit
    - nix build .#vmServer -L
  allow_failure: true

build-vm-cve-2022-0847-dirty-pipe:
  extends: .nix
  stage: build-vms
  script:
    - echo "Starting VM build for CVE-2022-0847 Dirty Pipe vulnerability..."
    - cd ./cves/cve-2022-0847-dirty-pipe
    - nix build .#vmServer -L
  allow_failure: true

build-vm-cve-2016-5195-dirty-cow:
  extends: .nix
  stage: build-vms
  script:
    - echo "Starting VM build for CVE-2016-5195 Dirty Cow vulnerability..."
    - cd ./cves/cve-2016-5195-dirty-cow
    - nix-build default.nix -A vmVulnerableTrue
  allow_failure: true

build-vm-cve-2014-0224-early-ccs:
  extends: .nix
  stage: build-vms
  script:
    - echo "Starting VM build for CVE-2014-0224 Early CCS vulnerability..."
    - cd ./cves/cve-2014-0224-early-ccs
    - echo "Building Server VM..."
    - nix build .#vmServer -L
    - echo "Building Client VM..."
    - nix build .#vmClient -L
  allow_failure: true

build-vm-cve-2022-25640-wolfssl:
  extends: .nix
  stage: build-vms
  script:
    - echo "Starting VM build for CVE-2022-25640 WolfSSL vulnerability..."
    - cd ./cves/cve-2022-25640-wolfssl
    - nix build .#vmServer -L
  allow_failure: true

build-vm-cve-2021-44228-log4shell:
  extends: .nix
  stage: build-vms
  script:
    - echo "Starting VM build for CVE-2021-44228 Log4Shell vulnerability..."
    - cd ./cves/cve-2021-44228-log4shell
    - echo "Building vulnerable server VM..."
    - nix build .#vmServer -L
    - echo "Building LDAP server VM..."
    - nix build .#vmLDAP -L
  allow_failure: true

build-vm-cve-2024-1135-gunicorn:
  extends: .nix
  stage: build-vms
  script:
    - echo "Starting VM build for CVE-2024-1135 Gunicorn vulnerability..."
    - cd ./cves/cve-2024-1135-gunicorn
    - echo "Building Gunicorn server VM..."
    - nix build .#vmServerVulnerable -L
  allow_failure: true

build-vm-cve-2025-32463-chwoot:
  extends: .nix
  stage: build-vms
  script:
    - echo "Starting VM build for CVE-2025-32463 Chwoot vulnerability..."
    - cd ./cves/cve-2025-32463-chwoot
    - echo "Building vulnerable VM..."
    - nix build .#vm -L
  allow_failure: true

build-vm-cve-2023-7028-gitlab-reset-email:
  extends: .nix
  stage: build-vms
  script:
    - echo "Starting VM build for CVE-2023-7028 GitLab reset email vulnerability..."
    - cd ./cves/cve-2023-7028-gitlab-email
    - echo "Building vulnerable GitLab server VM..."
    - nix build .#vmGitlabVulnerable -L
    - echo "Building email server VM..."
    - nix build .#vmMailServer -L
  allow_failure: true

build-vm-cve-2022-32278-graphical-libreoffice-rce:
  extends: .nix
  stage: build-vms
  script:
    - echo "Starting VM build for LibreOffice RCE vulnerability..."
    - cd ./cves/cve-2022-32278-graphical-libreoffice-rce
    - echo "Building local vulnerable LibreOffice VM..."
    - nix build .#vmLibreOfficeVulnLocal -L
    - echo "Building NFS vulnerable LibreOffice VM..."
    - nix build .#vmLibreOfficeVulnerableNFS -L
    - echo "Building NFS server VM..."
    - nix build .#vmNFS -L
    - echo "Building the interactive mode ..."
    - nix build .#testInteractiveVulnerableNFS -L
  allow_failure: true

build-vm-cve-2025-5399-curl-ws-loop:
  extends: .nix
  stage: build-vms
  script:
    - echo "Starting VM build for CVE-2025-5399 Curl WebSocket loop vulnerability..."
    - cd ./cves/cve-2025-5399-curl-ws-loop-3168039
    - echo "Building server VM..."
    - nix build .#vmServer -L
    - echo "Building vulnerable client VM..."
    - nix build .#vmClient -L
  allow_failure: true

build-vm-cve-2019-0221-tomcat-ssi-xss:
  extends: .nix
  stage: build-vms
  script:
    - echo "Starting VM build for CVE-2019-0221 Apache Tomcat SSI XSS vulnerability..."
    - cd ./cves/cve-2019-0221-apache-tomcat-ssi-xss
    - nix build .#vmServer -L
  allow_failure: true

build-vm-cve-2024-1071-wordpress-ultimate-member-sqli:
  extends: .nix
  stage: build-vms
  script:
    - echo "Starting VM build for CVE-2024-1071 WordPress Ultimate Member SQLi vulnerability..."
    - cd ./cves/cve-2024-1071-wordpress-sqli
    - echo "Building server VM..."
    - nix build .#vmServer -L
  allow_failure: true

build-vm-cve-2023-25666-tensorflow-audiospectrogram:
  extends: .nix
  stage: build-vms
  script:
    - echo "Starting VM build for CVE-2023-25666 TensorFlow AudioSpectrogram vulnerability..."
    - cd ./cves/cve-2023-25666-python-tensorflow
    - echo "Building vulnerable TensorFlow server VM..."
    - nix build .#vmVulnerableTrue -L
  allow_failure: true

build-vm-cve-2019-19725-sysstat-doublefree:
  extends: .nix
  stage: build-vms
  script:
    - echo "Starting VM build for CVE-2019-19725 Sysstat Double Free vulnerability..."
    - cd ./cves/cve-2019-19725-sysstat-doublefree
    - echo "Building server VM..."
    - nix build .#vmServer -L
  allow_failure: true

build-vm-cve-2021-40346-haproxy-http-smuggling:
  extends: .nix
  stage: build-vms
  script:
    - echo "Starting VM build for CVE-2021-40346 HAProxy HTTP Request Smuggling vulnerability..."
    - cd ./cves/cve-2021-40346-haproxy-http-smuggling
    - echo "Building server VM..."
    - nix build .#vmServer -L
    - echo "Building vulnerable HAProxy VM..."
    - nix build .#vmProxyVulnerableTrue -L
  allow_failure: true

# TESTING STAGE
#============================================================

test-nixos-cve-2020-7247-opensmtpd-rce:
  extends: .nix
  stage: test
  script:
    - echo "Running NixOS Remote code Execution test for CVE-2020-7247 OpenSMTPD vulnerability..."
    - cd ./cves/cve-2020-7247-opensmtpd
    - nix build .#testVulnerableTrue.driver -L
    - ./result/bin/nixos-test-driver
  needs: [build-vm-cve-2020-7247-opensmtpd]

test-nixos-cve-2014-0160-heartbleed:
  extends: .nix
  stage: test
  script:
    - echo "Running NixOS test for CVE-2014-0160 Heartbleed vulnerability..."
    - cd ./cves/cve-2014-0160-heartbleed
    - nix build .#testVulnerableTrue.driver -L
    - ./result/bin/nixos-test-driver
  needs: [build-vm-cve-2014-0160-heartbleed]

test-nixos-cve-2023-22809:
  extends: .nix
  stage: test
  script:
    - echo "Running NixOS test for CVE-2023-22809 vulnerability..."
    - cd ./cves/cve-2023-22809
    - nix build .#testVulnerableTrue -L
    - ./result/bin/nixos-test-driver
  needs: [build-vm-cve-2023-22809]

test-nixos-cve-2021-4034-pwnkit:
  extends: .nix
  stage: test
  script:
    - echo "Running NixOS test for CVE-2021-4034 PwnKit vulnerability..."
    - cd ./cves/cve-2021-4034-pwnkit
    - nix build .#testVulnerableTrue -L
    - ./result/bin/nixos-test-driver
  needs: [build-vm-cve-2021-4034-pwnkit]

test-nixos-cve-2022-0847-dirty-pipe:
  extends: .nix
  stage: test
  script:
    - echo "Running NixOS test for CVE-2022-0847 Dirty Pipe vulnerability..."
    - cd ./cves/cve-2022-0847-dirty-pipe
    - nix build .#testVulnerableTrue -L
    - ./result/bin/nixos-test-driver
  needs: [build-vm-cve-2022-0847-dirty-pipe]

test-nixos-cve-2016-5195-dirty-cow:
  extends: .nix
  stage: test
  script:
    - echo "Running NixOS test for CVE-2016-5195 Dirty Cow vulnerability..."
    - cd ./cves/cve-2016-5195-dirty-cow
    - nix-build default.nix -A testVulnerableTrue
    - ./result/bin/nixos-test-driver
  needs: [build-vm-cve-2016-5195-dirty-cow]

test-nixos-cve-2014-0224-early-ccs:
  extends: .nix
  stage: test
  script:
    - echo "Running NixOS test for CVE-2014-0224 Early CCS vulnerability..."
    - cd ./cves/cve-2014-0224-early-ccs
    - nix build .#testVulnerableTrue.driver -L
    - ./result/bin/nixos-test-driver
  needs: [build-vm-cve-2014-0224-early-ccs]

test-nixos-cve-2022-25640-wolfssl:
  extends: .nix
  stage: test
  script:
    - echo "Running NixOS test for CVE-2022-25640 WolfSSL vulnerability..."
    - cd ./cves/cve-2022-25640-wolfssl
    - nix build .#testVulnerableTrue.driver -L
    - ./result/bin/nixos-test-driver
  needs: [build-vm-cve-2022-25640-wolfssl]

test-nixos-cve-2021-44832-log4shell:
  extends: .nix
  stage: test
  script:
    - echo "Running NixOS test for CVE-2021-44832 Log4Shell vulnerability..."
    - cd ./cves/cve-2021-44228-log4shell
    - nix build .#testVulnerableTrue.driver -L
    - ./result/bin/nixos-test-driver
  needs: [build-vm-cve-2021-44228-log4shell]

test-nixos-cve-2024-1135-gunicorn:
  extends: .nix
  stage: test
  script:
    - echo "Running NixOS test for CVE-2024-1135 Gunicorn vulnerability..."
    - cd ./cves/cve-2024-1135-gunicorn
    - nix build .#testVulnerableTrue.driver -L
    - ./result/bin/nixos-test-driver
  needs: [build-vm-cve-2024-1135-gunicorn]

test-nixos-cve-2025-32463-chwoot:
  extends: .nix
  stage: test
  script:
    - echo "Running NixOS test for CVE-2025-32463 Chwoot vulnerability..."
    - cd ./cves/cve-2025-32463-chwoot
    - echo "Testing vulnerable VM..."
    - nix build .#testVulnerableTrue.driver -L
    - ./result/bin/nixos-test-driver
  needs: [build-vm-cve-2025-32463-chwoot]

test-nixos-cve-2023-7028-gitlab-reset-email:
  extends: .nix
  stage: test
  script:
    - echo "Running GitLab reset email test..."
    - cd ./cves/cve-2023-7028-gitlab-email
    - nix build .#testVulnerableTrue.driver -L
    - ./result/bin/nixos-test-driver
  needs: [build-vm-cve-2023-7028-gitlab-reset-email]

test-nixos-cve-2022-32278-graphical-libreoffice-rce:
  extends: .nix
  stage: test
  script:
    - echo "Running LibreOffice RCE test..."
    - cd ./cves/cve-2022-32278-graphical-libreoffice-rce
    - echo "Running LibreOffice Local exploit test..."
    - nix build .#testVulnerableLocal.driver -L
    - ./result/bin/nixos-test-driver
    - echo "Running LibreOffice NFS exploit test..."
    - nix build .#testVulnerableNFS -L
    - ./result/bin/nixos-test-driver
  needs: [build-vm-cve-2022-32278-graphical-libreoffice-rce]

test-nixos-cve-2025-5399-curl-ws-loop:
  extends: .nix
  stage: test
  script:
    - echo "Running Curl WebSocket loop test..."
    - cd ./cves/cve-2025-5399-curl-ws-loop-3168039
    - echo "Running WebSocket loop exploit test..."
    - nix build .#testVulnerableTrue.driver -L
    - ./result/bin/nixos-test-driver
  needs: [build-vm-cve-2025-5399-curl-ws-loop]

test-nixos-cve-2019-0221-tomcat-ssi-xss:
  extends: .nix
  stage: test
  script:
    - echo "Running Apache Tomcat SSI XSS test..."
    - cd ./cves/cve-2019-0221-apache-tomcat-ssi-xss
    - echo "Running SSI XSS exploit test..."
    - nix build .#testVulnerableTrue.driver -L
    - ./result/bin/nixos-test-driver
  needs: [build-vm-cve-2019-0221-tomcat-ssi-xss]

test-nixos-cve-2024-1071-wordpress-ultimate-member-sqli:
  extends: .nix
  stage: test
  script:
    - echo "Running WordPress Ultimate Member SQLi test..."
    - cd ./cves/cve-2024-1071-wordpress-sqli
    - echo "Running SQL Injection exploit test..."
    - nix build .#testVulnerableTrue.driver -L
    - ./result/bin/nixos-test-driver
  needs: [build-vm-cve-2024-1071-wordpress-ultimate-member-sqli]

test-nixos-cve-2023-25666-tensorflow-audiospectrogram:
  extends: .nix
  stage: test
  script:
    - echo "Running TensorFlow AudioSpectrogram test for CVE-2023-25666 vulnerability..."
    - cd ./cves/cve-2023-25666-python-tensorflow
    - nix build .#testVulnerableTrue.driver -L
    - ./result/bin/nixos-test-driver
  needs: [build-vm-cve-2023-25666-tensorflow-audiospectrogram]

test-nixos-cve-2019-19725-sysstat-doublefree:
  extends: .nix
  stage: test
  script:
    - echo "Running Sysstat Double Free test for CVE-2019-19725 vulnerability..."
    - cd ./cves/cve-2019-19725-sysstat-doublefree
    - nix build .#testVulnerableTrue.driver -L
    - ./result/bin/nixos-test-driver
  needs: [build-vm-cve-2019-19725-sysstat-doublefree]

test-nixos-cve-2021-40346-haproxy-http-smuggling:
  extends: .nix
  stage: test
  script:
    - echo "Running HAProxy HTTP Request Smuggling test for CVE-2021-40346 vulnerability..."
    - cd ./cves/cve-2021-40346-haproxy-http-smuggling
    - nix build .#testVulnerableTrue.driver -L
    - ./result/bin/nixos-test-driver
  needs: [build-vm-cve-2021-40346-haproxy-http-smuggling]